version: '3.5'

# Please make a copy of .env.template (renamed as .env) and populate variables there
# To start Gigwa and mongo together, run docker-compose up -d

services:
  tomcat:
    depends_on:
      - mongo
    image: ${GIGWA_DOCKER_IMAGE:-guilhemsempere/gigwa:2.5.2-snapshot}
    container_name: ${GIGWA_CONTAINER_NAME:-gigwa}
    ports:
      - ${GIGWA_PORT:-8080}:8080 # You may amend the external port only (left hand side). By default, webapp URL will be http://host.ip:8080/gigwa
    restart: always
    environment:
      MONGO_IP: ${GIGWA_MONGO_HOST:-gigwa_db}
      MONGO_PORT: ${GIGWA_MONGO_PORT:-27017}
      MONGO_INITDB_ROOT_USERNAME: ${GIGWA_MONGO_USER:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${GIGWA_MONGO_PASSWORD:-mongo}
      HOST_LOCALE: "${LANG}"
      #     casServerURL: https://sso.cirad.fr:443                # URL of the CAS server to use for Single-Sign-On
      #     enforcedWebapRootUrl: http://${docker0}:8080/gigwa    # Gigwa base-URL for CAS to direct to after login. System will attempt guessing it if not provided, but it's always better to specify it
      #     casOrganization: MyOrganization                       # Not required, will only be displayed on login page if provided

    volumes:
      - type: volume
        source: gigwa_data
        target: /usr/local/tomcat/config
  #      - type: bind                      # Uncomment this line to make dumps accessible from the host machine
  #        source: /tmp/gigwaDockerDumps   # Uncomment this line to make dumps accessible from the host machine (you may also want to set the path you wish to use as source)
  #        target: /root/gigwaDumps        # Uncomment this line to make dumps accessible from the host machine (must match the dumpFolder attribute's value in config.properties)
  mongo:
    image: ${MONGO_DOCKER_IMAGE:-mongo:4.2.21}
    container_name: ${GIGWA_CONTAINER_NAME:-gigwa}_db
    restart: always
    command: --profile 0 --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zstd --directoryperdb --quiet
    ports:
      - ${GIGWA_MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${GIGWA_MONGO_USER:-mongo}
      MONGO_INITDB_ROOT_PASSWORD: ${GIGWA_MONGO_PASSWORD:-mongo}
    volumes:
      - type: volume
        source: gigwa_mongo_data
        target: /data/db

volumes:
  gigwa_data:
    name: ${GIGWA_CONTAINER_NAME:-gigwa}_data
  gigwa_mongo_data:
    name: ${GIGWA_CONTAINER_NAME:-gigwa}_mongo_data